[package]
name = "task_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"

uuid = { version = "1.18.0", features = ["v4"] }

serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
